/**
 * @packageDocumentation
 * @module api.functional.clubs.me.applied
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { Club } from "../../../../structures/Club";

/**
 * 내가 신청한 동아리 목록 조회
 *
 * @tag clubs
 * @summary 내가 신청한 동아리 목록 조회
 * @returns 내가 신청한 동아리 목록
 *
 * @controller ClubsController.getMyAppliedClubs
 * @path GET /clubs/me/applied
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMyAppliedClubs(
  connection: IConnection,
): Promise<getMyAppliedClubs.Output> {
  return true === connection.simulate
    ? getMyAppliedClubs.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getMyAppliedClubs.METADATA,
        template: getMyAppliedClubs.METADATA.path,
        path: getMyAppliedClubs.path(),
      });
}
export namespace getMyAppliedClubs {
  export type Output = Club[];

  export const METADATA = {
    method: "GET",
    path: "/clubs/me/applied",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/clubs/me/applied";
  export const random = (): Resolved<Club[]> => typia.random<Club[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
