/**
 * @packageDocumentation
 * @module api.functional.users.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { User } from "../../../structures/User";

/**
 * 내 정보 조회
 *
 * @tag users
 * @summary 로그인한 사용자의 마이페이지 정보 조회
 * @returns 내 정보
 *
 * @controller UsersController.getMyPage
 * @path GET /users/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMyPage(
  connection: IConnection,
): Promise<getMyPage.Output> {
  return true === connection.simulate
    ? getMyPage.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getMyPage.METADATA,
        template: getMyPage.METADATA.path,
        path: getMyPage.path(),
      });
}
export namespace getMyPage {
  export type Output = User.o2;

  export const METADATA = {
    method: "GET",
    path: "/users/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/users/me";
  export const random = (): Resolved<User.o2> => typia.random<User.o2>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
