/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";
import type { Minimum } from "typia/lib/tags/Minimum";
import type { Type } from "typia/lib/tags/Type";

import type { CreateUserDto } from "../../structures/CreateUserDto";
import type { User } from "../../structures/User";

export * as me from "./me";

/**
 * 새로운 사용자 생성
 *
 * @param dto 사용자 생성 정보
 * @tag users
 * @summary 새로운 사용자 생성
 * @returns 생성된 사용자 정보
 *
 * @controller UsersController.createUser
 * @path POST /users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createUser(
  connection: IConnection,
  dto: createUser.Body,
): Promise<createUser.Output> {
  return true === connection.simulate
    ? createUser.simulate(connection, dto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createUser.METADATA,
          template: createUser.METADATA.path,
          path: createUser.path(),
        },
        dto,
      );
}
export namespace createUser {
  export type Body = CreateUserDto;
  export type Output = User.o2;

  export const METADATA = {
    method: "POST",
    path: "/users",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/users";
  export const random = (): Resolved<User.o2> => typia.random<User.o2>();
  export const simulate = (connection: IConnection, dto: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(dto));
    return random();
  };
}

/**
 * 사용자 상세 정보 조회
 *
 * @param userId 사용자 ID
 * @tag users
 * @summary 특정 사용자의 상세 정보 조회
 * @returns 사용자 상세 정보
 *
 * @controller UsersController.getUserDetail
 * @path GET /users/:userId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserDetail(
  connection: IConnection,
  userId: number & Type<"int32"> & Minimum<1>,
): Promise<getUserDetail.Output> {
  return true === connection.simulate
    ? getUserDetail.simulate(connection, userId)
    : PlainFetcher.fetch(connection, {
        ...getUserDetail.METADATA,
        template: getUserDetail.METADATA.path,
        path: getUserDetail.path(userId),
      });
}
export namespace getUserDetail {
  export type Output = User.o2;

  export const METADATA = {
    method: "GET",
    path: "/users/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (userId: number & Type<"int32"> & Minimum<1>) =>
    `/users/${encodeURIComponent(userId?.toString() ?? "null")}`;
  export const random = (): Resolved<User.o2> => typia.random<User.o2>();
  export const simulate = (
    connection: IConnection,
    userId: number & Type<"int32"> & Minimum<1>,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(userId),
      contentType: "application/json",
    });
    assert.param("userId")(() => typia.assert(userId));
    return random();
  };
}
