version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@${KAFKA_HOST}:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://${KAFKA_HOST}:29092,CONTROLLER://${KAFKA_HOST}:29093,PLAINTEXT_HOST://0.0.0.0:${KAFKA_PORT}'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${KAFKA_HOST}:29092,PLAINTEXT_HOST://${KAFKA_HOST}:${KAFKA_PORT}'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network

  kafka-init:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: [ 'sh', '-c' ]
    command: >
      echo "Waiting for Kafka..." &&
      sleep 10 &&
      kafka-topics --bootstrap-server ${KAFKA_HOST}:${KAFKA_PORT} --list &&
      echo "Creating kafka topics" &&
      kafka-topics --bootstrap-server ${KAFKA_HOST}:${KAFKA_PORT} --create --if-not-exists --topic logs --replication-factor 1 --partitions 3 &&
      echo "Successfully created topics:" &&
      kafka-topics --bootstrap-server ${KAFKA_HOST}:${KAFKA_PORT} --list
    networks:
      - app-network

  nestjs:
    build: .
    container_name: nestjs-app
    ports:
      - "${PORT_NESTJS}:3000"
    networks:
      - app-network
      - monitoring
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - kafka-init

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PORT_PROMETHEUS}:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${PORT_GRAFANA}:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data: