/**
 * @packageDocumentation
 * @module api.functional.logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { GetAllLogsDto } from "../../structures/GetAllLogsDto";
import type { Log } from "../../structures/Log";

export * as user from "./user";
export * as club from "./club";
export * as action from "./action";

/**
 * 모든 로그를 조회합니다. 날짜 범위로 필터링 가능합니다.
 *
 * @param query 쿼리 파라미터 (page, limit, startDate, endDate)
 * @tag logs
 * @summary 전체 로그 조회
 * @returns 전체 로그 목록
 *
 * @controller LogsController.getAllLogs
 * @path GET /logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllLogs(
  connection: IConnection,
  query: getAllLogs.Query,
): Promise<getAllLogs.Output> {
  return true === connection.simulate
    ? getAllLogs.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...getAllLogs.METADATA,
        template: getAllLogs.METADATA.path,
        path: getAllLogs.path(query),
      });
}
export namespace getAllLogs {
  export type Query = GetAllLogsDto;
  export type Output = Log.o1[];

  export const METADATA = {
    method: "GET",
    path: "/logs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/logs";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Log.o1[]> => typia.random<Log.o1[]>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}
