/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

/**
 * 애플리케이션 헬스 체크 엔드포인트
 * 서버의 현재 상태, 가동 시간, 메모리 사용량 등의 기본 정보를 반환합니다.
 *
 * @tag Prometheus
 * @returns 헬스 체크 결과 객체
 * @property {string} status - 서버 상태 ('ok')
 * @property {string} timestamp - 현재 시간 ISO 문자열
 * @property {number} uptime - 서버 가동 시간 (초)
 * @property {NodeJS.MemoryUsage} memory - 메모리 사용량 정보
 *
 * @controller HealthController.healthCheck
 * @path GET /health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function healthCheck(
  connection: IConnection,
): Promise<healthCheck.Output> {
  return true === connection.simulate
    ? healthCheck.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...healthCheck.METADATA,
        template: healthCheck.METADATA.path,
        path: healthCheck.path(),
      });
}
export namespace healthCheck {
  export type Output = {};

  export const METADATA = {
    method: "GET",
    path: "/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health";
  export const random = (): Resolved<{}> => typia.random<{}>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
