/**
 * @packageDocumentation
 * @module api.functional.clubs.bookmark
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { BookmarkClubDto } from "../../../structures/BookmarkClubDto";
import type { SuccessResponse } from "../../../structures/SuccessResponse";

/**
 * 동아리 북마크 토글
 *
 * @param dto 북마크할 동아리 정보
 * @tag clubs
 * @summary 동아리 북마크 추가/제거
 * @returns 북마크 처리 결과
 *
 * @controller ClubsController.bookmarkClub
 * @path POST /clubs/bookmark
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function bookmarkClub(
  connection: IConnection,
  dto: bookmarkClub.Body,
): Promise<bookmarkClub.Output> {
  return true === connection.simulate
    ? bookmarkClub.simulate(connection, dto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...bookmarkClub.METADATA,
          template: bookmarkClub.METADATA.path,
          path: bookmarkClub.path(),
        },
        dto,
      );
}
export namespace bookmarkClub {
  export type Body = BookmarkClubDto;
  export type Output = SuccessResponse;

  export const METADATA = {
    method: "POST",
    path: "/clubs/bookmark",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/clubs/bookmark";
  export const random = (): Resolved<SuccessResponse> =>
    typia.random<SuccessResponse>();
  export const simulate = (connection: IConnection, dto: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(dto));
    return random();
  };
}
