/**
 * @packageDocumentation
 * @module api.functional.admin.registration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as open from "./open";
export * as close from "./close";
