/**
 * @packageDocumentation
 * @module api.functional.logs.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { Log } from "../../../structures/Log";
import type { PaginationDto } from "../../../structures/PaginationDto";

/**
 * 특정 사용자의 로그를 조회합니다.
 *
 * @param pagination 페이지네이션 정보
 * @tag logs
 * @summary 사용자별 로그 조회
 * @returns 사용자의 로그 목록
 *
 * @controller LogsController.getLogsByUser
 * @path GET /logs/user/:userId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLogsByUser(
  connection: IConnection,
  userId: number,
  pagination: getLogsByUser.Query,
): Promise<getLogsByUser.Output> {
  return true === connection.simulate
    ? getLogsByUser.simulate(connection, userId, pagination)
    : PlainFetcher.fetch(connection, {
        ...getLogsByUser.METADATA,
        template: getLogsByUser.METADATA.path,
        path: getLogsByUser.path(userId, pagination),
      });
}
export namespace getLogsByUser {
  export type Query = PaginationDto;
  export type Output = Log.o1[];

  export const METADATA = {
    method: "GET",
    path: "/logs/user/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (userId: number, pagination: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(pagination as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/logs/user/${encodeURIComponent(userId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Log.o1[]> => typia.random<Log.o1[]>();
  export const simulate = (
    connection: IConnection,
    userId: number,
    pagination: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(userId, pagination),
      contentType: "application/json",
    });
    assert.param("userId")(() => typia.assert(userId));
    assert.query(() => typia.assert(pagination));
    return random();
  };
}
