/**
 * @packageDocumentation
 * @module api.functional.health.metrics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

/**
 * Prometheus 메트릭 엔드포인트 정보 제공
 * 실제 메트릭 데이터가 아닌 메트릭 엔드포인트의 가용성을 확인하는 용도입니다.
 * 실제 Prometheus 메트릭 데이터는 '/metrics' 엔드포인트에서 확인할 수 있습니다.
 *
 * @returns 메트릭 엔드포인트 정보
 * @property {string} status - 메트릭 엔드포인트 상태
 * @property {string} endpoint - 실제 메트릭 데이터 엔드포인트 경로
 *
 * @controller HealthController.getMetrics
 * @path GET /health/metrics
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getMetrics(
  connection: IConnection,
): Promise<getMetrics.Output> {
  return true === connection.simulate
    ? getMetrics.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getMetrics.METADATA,
        template: getMetrics.METADATA.path,
        path: getMetrics.path(),
      });
}
export namespace getMetrics {
  export type Output = {
    status: string;
    endpoint: string;
  };

  export const METADATA = {
    method: "GET",
    path: "/health/metrics",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health/metrics";
  export const random = (): Resolved<{
    status: string;
    endpoint: string;
  }> =>
    typia.random<{
      status: string;
      endpoint: string;
    }>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
