/**
 * @packageDocumentation
 * @module api.functional.clubs.me.bookmarked
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { Club } from "../../../../structures/Club";

/**
 * 내가 북마크한 동아리 목록 조회
 *
 * @tag clubs
 * @summary 북마크한 동아리 목록 조회
 * @returns 북마크한 동아리 목록
 *
 * @controller ClubsController.getBookmarkedClubs
 * @path GET /clubs/me/bookmarked
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getBookmarkedClubs(
  connection: IConnection,
): Promise<getBookmarkedClubs.Output> {
  return true === connection.simulate
    ? getBookmarkedClubs.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getBookmarkedClubs.METADATA,
        template: getBookmarkedClubs.METADATA.path,
        path: getBookmarkedClubs.path(),
      });
}
export namespace getBookmarkedClubs {
  export type Output = Club[];

  export const METADATA = {
    method: "GET",
    path: "/clubs/me/bookmarked",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/clubs/me/bookmarked";
  export const random = (): Resolved<Club[]> => typia.random<Club[]>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
