/**
 * @packageDocumentation
 * @module api.functional.admin.registration.open
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { RegistrationResponse } from "../../../../structures/RegistrationResponse";
import type { SetRegistrationPeriodDto } from "../../../../structures/SetRegistrationPeriodDto";

/**
 * 동아리 모집 기간 시작
 *
 * @param dto 모집 기간 설정 정보
 * @tag admin
 * @summary 동아리 모집 기간을 설정하고 시작
 * @returns 모집 시작 처리 결과
 *
 * @controller AdminController.openRegistration
 * @path POST /admin/registration/open
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function openRegistration(
  connection: IConnection,
  dto: openRegistration.Body,
): Promise<openRegistration.Output> {
  return true === connection.simulate
    ? openRegistration.simulate(connection, dto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...openRegistration.METADATA,
          template: openRegistration.METADATA.path,
          path: openRegistration.path(),
        },
        dto,
      );
}
export namespace openRegistration {
  export type Body = SetRegistrationPeriodDto;
  export type Output = RegistrationResponse;

  export const METADATA = {
    method: "POST",
    path: "/admin/registration/open",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/admin/registration/open";
  export const random = (): Resolved<RegistrationResponse> =>
    typia.random<RegistrationResponse>();
  export const simulate = (connection: IConnection, dto: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(dto));
    return random();
  };
}
