/**
 * @packageDocumentation
 * @module api.functional.clubs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";
import type { Minimum } from "typia/lib/tags/Minimum";
import type { Type } from "typia/lib/tags/Type";

import type { Club } from "../../structures/Club";
import type { ClubListQuery } from "../../structures/ClubListQuery";
import type { CreateClubDto } from "../../structures/CreateClubDto";

export * as apply from "./apply";
export * as bookmark from "./bookmark";
export * as me from "./me";

/**
 * 동아리 목록 조회
 *
 * @tag clubs
 * @summary 동아리 목록 조회
 * @returns 동아리 목록
 *
 * @controller ClubsController.getClubList
 * @path GET /clubs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getClubList(
  connection: IConnection,
  query: getClubList.Query,
): Promise<getClubList.Output> {
  return true === connection.simulate
    ? getClubList.simulate(connection, query)
    : PlainFetcher.fetch(connection, {
        ...getClubList.METADATA,
        template: getClubList.METADATA.path,
        path: getClubList.path(query),
      });
}
export namespace getClubList {
  export type Query = ClubListQuery;
  export type Output = Club[];

  export const METADATA = {
    method: "GET",
    path: "/clubs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/clubs";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Club[]> => typia.random<Club[]>();
  export const simulate = (connection: IConnection, query: Query): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    assert.query(() => typia.assert(query));
    return random();
  };
}

/**
 * 동아리 상세 정보 조회
 *
 * @param clubId 동아리 ID
 * @tag clubs
 * @summary 동아리 상세 정보 조회
 * @returns 동아리 상세 정보
 *
 * @controller ClubsController.getClubDetail
 * @path GET /clubs/:clubId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getClubDetail(
  connection: IConnection,
  clubId: number & Type<"int32"> & Minimum<1>,
): Promise<getClubDetail.Output> {
  return true === connection.simulate
    ? getClubDetail.simulate(connection, clubId)
    : PlainFetcher.fetch(connection, {
        ...getClubDetail.METADATA,
        template: getClubDetail.METADATA.path,
        path: getClubDetail.path(clubId),
      });
}
export namespace getClubDetail {
  export type Output = Club;

  export const METADATA = {
    method: "GET",
    path: "/clubs/:clubId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clubId: number & Type<"int32"> & Minimum<1>) =>
    `/clubs/${encodeURIComponent(clubId?.toString() ?? "null")}`;
  export const random = (): Resolved<Club> => typia.random<Club>();
  export const simulate = (
    connection: IConnection,
    clubId: number & Type<"int32"> & Minimum<1>,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(clubId),
      contentType: "application/json",
    });
    assert.param("clubId")(() => typia.assert(clubId));
    return random();
  };
}

/**
 * 동아리 생성
 *
 * @param dto 동아리 생성 정보
 * @tag clubs
 * @summary 새로운 동아리 생성
 * @returns 생성된 동아리 정보
 *
 * @controller ClubsController.createClub
 * @path POST /clubs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createClub(
  connection: IConnection,
  dto: createClub.Body,
): Promise<createClub.Output> {
  return true === connection.simulate
    ? createClub.simulate(connection, dto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createClub.METADATA,
          template: createClub.METADATA.path,
          path: createClub.path(),
        },
        dto,
      );
}
export namespace createClub {
  export type Body = CreateClubDto;
  export type Output = Club;

  export const METADATA = {
    method: "POST",
    path: "/clubs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/clubs";
  export const random = (): Resolved<Club> => typia.random<Club>();
  export const simulate = (connection: IConnection, dto: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(dto));
    return random();
  };
}
