/**
 * @packageDocumentation
 * @module api.functional.clubs.apply
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";
import type { Minimum } from "typia/lib/tags/Minimum";
import type { Type } from "typia/lib/tags/Type";

import type { SuccessResponse } from "../../../structures/SuccessResponse";

/**
 * 동아리 가입 신청
 *
 * @param clubId 동아리 ID
 * @tag clubs
 * @summary 동아리 가입 신청
 * @returns 가입 신청된 동아리 정보
 *
 * @controller ClubsController.applyClub
 * @path POST /clubs/:clubId/apply
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function applyClub(
  connection: IConnection,
  clubId: number & Type<"int32"> & Minimum<1>,
): Promise<applyClub.Output> {
  return true === connection.simulate
    ? applyClub.simulate(connection, clubId)
    : PlainFetcher.fetch(connection, {
        ...applyClub.METADATA,
        template: applyClub.METADATA.path,
        path: applyClub.path(clubId),
      });
}
export namespace applyClub {
  export type Output = SuccessResponse;

  export const METADATA = {
    method: "POST",
    path: "/clubs/:clubId/apply",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (clubId: number & Type<"int32"> & Minimum<1>) =>
    `/clubs/${encodeURIComponent(clubId?.toString() ?? "null")}/apply`;
  export const random = (): Resolved<SuccessResponse> =>
    typia.random<SuccessResponse>();
  export const simulate = (
    connection: IConnection,
    clubId: number & Type<"int32"> & Minimum<1>,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(clubId),
      contentType: "application/json",
    });
    assert.param("clubId")(() => typia.assert(clubId));
    return random();
  };
}

/**
 * 동아리 신청 취소
 *
 * @param clubId 동아리 ID
 * @tag clubs
 * @summary 동아리 신청 취소
 * @returns 취소 결과
 *
 * @controller ClubsController.cancelApplyClub
 * @path DELETE /clubs/:clubId/apply
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cancelApplyClub(
  connection: IConnection,
  clubId: number & Type<"int32"> & Minimum<1>,
): Promise<cancelApplyClub.Output> {
  return true === connection.simulate
    ? cancelApplyClub.simulate(connection, clubId)
    : PlainFetcher.fetch(connection, {
        ...cancelApplyClub.METADATA,
        template: cancelApplyClub.METADATA.path,
        path: cancelApplyClub.path(clubId),
      });
}
export namespace cancelApplyClub {
  export type Output = SuccessResponse;

  export const METADATA = {
    method: "DELETE",
    path: "/clubs/:clubId/apply",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clubId: number & Type<"int32"> & Minimum<1>) =>
    `/clubs/${encodeURIComponent(clubId?.toString() ?? "null")}/apply`;
  export const random = (): Resolved<SuccessResponse> =>
    typia.random<SuccessResponse>();
  export const simulate = (
    connection: IConnection,
    clubId: number & Type<"int32"> & Minimum<1>,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(clubId),
      contentType: "application/json",
    });
    assert.param("clubId")(() => typia.assert(clubId));
    return random();
  };
}
