/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { LoginDto } from "../../structures/LoginDto";

/**
 * 구글 OAuth 로그인
 *
 * @param dto 로그인 정보 (idToken)
 * @tag auth
 * @summary 구글 OAuth 로그인
 * @returns 로그인 성공 여부 및 토큰
 *
 * @controller AuthController.google
 * @path POST /auth/google
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function google(
  connection: IConnection,
  dto: google.Body,
): Promise<google.Output> {
  return true === connection.simulate
    ? google.simulate(connection, dto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...google.METADATA,
          template: google.METADATA.path,
          path: google.path(),
        },
        dto,
      );
}
export namespace google {
  export type Body = LoginDto;
  export type Output =
    | {
        success: boolean;
        token: string;
      }
    | {
        success: boolean;
        token?: undefined;
      };

  export const METADATA = {
    method: "POST",
    path: "/auth/google",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/google";
  export const random = (): Resolved<
    | {
        success: boolean;
        token: string;
      }
    | {
        success: boolean;
        token?: undefined;
      }
  > =>
    typia.random<
      | {
          success: boolean;
          token: string;
        }
      | {
          success: boolean;
          token?: undefined;
        }
    >();
  export const simulate = (connection: IConnection, dto: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(dto));
    return random();
  };
}
