/**
 * @packageDocumentation
 * @module api.functional.admin.registration.close
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { CloseRegistrationDto } from "../../../../structures/CloseRegistrationDto";
import type { RegistrationResponse } from "../../../../structures/RegistrationResponse";

/**
 * 동아리 모집 기간 종료
 *
 * @param dto 모집 종료 정보
 * @tag admin
 * @summary 동아리 모집 기간을 조기 종료
 * @returns 모집 종료 처리 결과
 *
 * @controller AdminController.closeRegistration
 * @path POST /admin/registration/close
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function closeRegistration(
  connection: IConnection,
  dto: closeRegistration.Body,
): Promise<closeRegistration.Output> {
  return true === connection.simulate
    ? closeRegistration.simulate(connection, dto)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...closeRegistration.METADATA,
          template: closeRegistration.METADATA.path,
          path: closeRegistration.path(),
        },
        dto,
      );
}
export namespace closeRegistration {
  export type Body = CloseRegistrationDto;
  export type Output = RegistrationResponse;

  export const METADATA = {
    method: "POST",
    path: "/admin/registration/close",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/admin/registration/close";
  export const random = (): Resolved<RegistrationResponse> =>
    typia.random<RegistrationResponse>();
  export const simulate = (connection: IConnection, dto: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(dto));
    return random();
  };
}
