/**
 * @packageDocumentation
 * @module api.functional.logs.club
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { Log } from "../../../structures/Log";
import type { PaginationDto } from "../../../structures/PaginationDto";

/**
 * 특정 동아리의 로그를 조회합니다.
 *
 * @param clubId 조회할 동아리의 ID
 * @param pagination 페이지네이션 정보
 * @tag logs
 * @summary 동아리별 로그 조회
 * @returns 동아리의 로그 목록
 *
 * @controller LogsController.getLogsByClub
 * @path GET /logs/club/:clubId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLogsByClub(
  connection: IConnection,
  clubId: number,
  pagination: getLogsByClub.Query,
): Promise<getLogsByClub.Output> {
  return true === connection.simulate
    ? getLogsByClub.simulate(connection, clubId, pagination)
    : PlainFetcher.fetch(connection, {
        ...getLogsByClub.METADATA,
        template: getLogsByClub.METADATA.path,
        path: getLogsByClub.path(clubId, pagination),
      });
}
export namespace getLogsByClub {
  export type Query = PaginationDto;
  export type Output = Log.o1[];

  export const METADATA = {
    method: "GET",
    path: "/logs/club/:clubId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clubId: number, pagination: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(pagination as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/logs/club/${encodeURIComponent(clubId?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Log.o1[]> => typia.random<Log.o1[]>();
  export const simulate = (
    connection: IConnection,
    clubId: number,
    pagination: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(clubId, pagination),
      contentType: "application/json",
    });
    assert.param("clubId")(() => typia.assert(clubId));
    assert.query(() => typia.assert(pagination));
    return random();
  };
}
