/**
 * @packageDocumentation
 * @module api.functional.logs.action
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";
import typia from "typia";

import type { Log } from "../../../structures/Log";
import type { PaginationDto } from "../../../structures/PaginationDto";

/**
 * 특정 액션의 로그를 조회합니다.
 *
 * @param action 조회할 액션 (CREATE, APPLY, BOOKMARK 등)
 * @param pagination 페이지네이션 정보
 * @tag logs
 * @summary 액션별 로그 조회
 * @returns 액션의 로그 목록
 *
 * @controller LogsController.getLogsByAction
 * @path GET /logs/action/:action
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLogsByAction(
  connection: IConnection,
  action:
    | "APPLY"
    | "CANCEL_APPLY"
    | "BOOKMARK"
    | "UNBOOKMARK"
    | "VIEW_CLUB_LIST"
    | "VIEW_CLUB_DETAIL"
    | "VIEW_MY_PAGE"
    | "CREATE_CLUB"
    | "UPDATE_CLUB"
    | "DELETE_CLUB"
    | "VIEW_APPLICANTS"
    | "EXPORT_APPLICANTS"
    | "VIEW_TEACHER_PAGE"
    | "IMPORT_USERS_CSV"
    | "IMPORT_CLUBS_CSV"
    | "AUTO_CLOSE_CLUB"
    | "AUTO_OPEN_CLUB"
    | "LOGIN"
    | "LOGOUT"
    | "REGISTER",
  pagination: getLogsByAction.Query,
): Promise<getLogsByAction.Output> {
  return true === connection.simulate
    ? getLogsByAction.simulate(connection, action, pagination)
    : PlainFetcher.fetch(connection, {
        ...getLogsByAction.METADATA,
        template: getLogsByAction.METADATA.path,
        path: getLogsByAction.path(action, pagination),
      });
}
export namespace getLogsByAction {
  export type Query = PaginationDto;
  export type Output = Log.o1[];

  export const METADATA = {
    method: "GET",
    path: "/logs/action/:action",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    action:
      | "APPLY"
      | "CANCEL_APPLY"
      | "BOOKMARK"
      | "UNBOOKMARK"
      | "VIEW_CLUB_LIST"
      | "VIEW_CLUB_DETAIL"
      | "VIEW_MY_PAGE"
      | "CREATE_CLUB"
      | "UPDATE_CLUB"
      | "DELETE_CLUB"
      | "VIEW_APPLICANTS"
      | "EXPORT_APPLICANTS"
      | "VIEW_TEACHER_PAGE"
      | "IMPORT_USERS_CSV"
      | "IMPORT_CLUBS_CSV"
      | "AUTO_CLOSE_CLUB"
      | "AUTO_OPEN_CLUB"
      | "LOGIN"
      | "LOGOUT"
      | "REGISTER",
    pagination: Query,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(pagination as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/logs/action/${encodeURIComponent(action?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (): Resolved<Log.o1[]> => typia.random<Log.o1[]>();
  export const simulate = (
    connection: IConnection,
    action:
      | "APPLY"
      | "CANCEL_APPLY"
      | "BOOKMARK"
      | "UNBOOKMARK"
      | "VIEW_CLUB_LIST"
      | "VIEW_CLUB_DETAIL"
      | "VIEW_MY_PAGE"
      | "CREATE_CLUB"
      | "UPDATE_CLUB"
      | "DELETE_CLUB"
      | "VIEW_APPLICANTS"
      | "EXPORT_APPLICANTS"
      | "VIEW_TEACHER_PAGE"
      | "IMPORT_USERS_CSV"
      | "IMPORT_CLUBS_CSV"
      | "AUTO_CLOSE_CLUB"
      | "AUTO_OPEN_CLUB"
      | "LOGIN"
      | "LOGOUT"
      | "REGISTER",
    pagination: Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(action, pagination),
      contentType: "application/json",
    });
    assert.param("action")(() => typia.assert(action));
    assert.query(() => typia.assert(pagination));
    return random();
  };
}
